{% set name = "pytoolconfig" %}
{% set version = "1.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pytoolconfig-{{ version }}.tar.gz
  sha256: 5ac82f78d731531f9f82e5cc7f5ebae9473b1404c0e75aa5ac0b8b41cd99b510

build:
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python
  number: 0

requirements:
  host:
    - pip
    - pdm
    - python >=3.6
  run:
    - packaging >=21.3
    - python >=3.6
    - tomli >=2.0
    - typing-extensions

test:
  imports:
    - pytoolconfig
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/pytoolconfig/
  summary: Python tool configuration
  license: LGPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
