{% set name = "pytoolconfig" %}
{% set version = "1.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pytoolconfig-{{ version }}.tar.gz
  sha256: 2512a1f261a40e73cef2e58e786184261b60c802ae7ed01249342b1949ec3aa2

build:
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python
  number: 0

requirements:
  host:
    - pip
    - pdm
    - python >=3.6
  run:
    - packaging >=21.3
    - python >=3.6
    - tomli >=2.0
    - typing-extensions

test:
  imports:
    - pytoolconfig
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/pytoolconfig/
  summary: Python tool configuration
  license: LGPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
