{% set version = "1.2.5" %}

package:
  name: pytoolconfig
  version: {{ version }}

source:
  url: https://github.com/bagel897/pytoolconfig/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 077daa343e0b865f30eadbd2a2fc778983a526311dd44f8ae31d17ba5bc1b126

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps
  skip: True # [py<37]
  number: 0

requirements:
  host:
    - pip
    - pdm
    - pdm-pep517
    - python
    - setuptools
    - wheel
  run:
    - packaging >=22.0
    - python
    - tomli >=2.0.1  # [py<311]
    - typing-extensions >=4.4.0  # [py<38]

test:
  imports:
    - pytoolconfig
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/bagel897/pytoolconfig
  dev_url: https://github.com/bagel897/pytoolconfig
  summary: Python tool configuration
  description: |
    Python tool configuration.
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_url: https://github.com/bagel897/pytoolconfig/blob/main/LICENSE
  doc_url: https://github.com/bagel897/pytoolconfig/blob/main/README.md

extra:
  recipe-maintainers:
    - jan-janssen