{% set name = "pytoolconfig" %}
{% set version = "1.2.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pytoolconfig-{{ version }}.tar.gz
  sha256: 5e1a246f77970ddb5f3d8d06fbf162424b8a1adfc22c2eb51826b383bf293d1e

build:
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python
  number: 0

requirements:
  host:
    - pip <22
    - pdm
    - pdm-pep517
    - python >=3.6
  run:
    - packaging >=21.3
    - python >=3.6
    - tomli >=2.0
    - typing-extensions

test:
  imports:
    - pytoolconfig
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/pytoolconfig/
  summary: Python tool configuration
  license: LGPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
